image: Visual Studio 2019

platform:
  - x86
  
environment:
  SIGNTOOL: C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64\signtool.exe

clone_depth: 1

init:
  - ps: $env:VERSION = if ($env:APPVEYOR_REPO_TAG_NAME) { $env:APPVEYOR_REPO_TAG_NAME } else { 'vdev' }

install:
  - nuget install secure-file -ExcludeVersion
  - secure-file\tools\secure-file -decrypt hardwario-cert.p12.enc -out hardwario-cert.p12 -secret %enc_secret%

build_script:
  - cmd: >-
      cmake .
      
      cmake --build . --config Release
      
      copy Release\enmon.exe "enmon_%VERSION%_win32.exe"
      
      dir
   
      "%SIGNTOOL%" sign /t http://timestamp.digicert.com /f hardwario-cert.p12 /p %CSC_KEY_PASSWORD% "enmon_%VERSION%_win32.exe"
      

artifacts:
  - path: enmon*.exe

deploy:
- provider: GitHub
  auth_token:
    secure: RW37naQWH0+y6BcxGzXjo6uZeLnDeYKy4wWhS+exbiZiaslB/TOMQrdXmuLyD/AF
  artifact: /.*\.exe/
  force_update: true
  on:
    appveyor_repo_tag: true
