language: c

os: linux
dist: xenial

stages:
  - build
  - deploy

jobs:
  include:
    - stage: build
      os: linux
      dist: focal
      addons:
        apt:
          - libudev-dev
          - cmake
      script:
        - cmake .
        - cmake --build .
        - mv enmon enmon_linux_x64
        - ls -lha
      workspaces:
        create:
          name: linux-binaries
          paths:
            - enmon*

    - stage: build
      os: osx
      script:
        - cmake .
        - cmake --build .
        - mv enmon enmon_darwin_x64
        - ls -lha
      workspaces:
        create:
          name: osx-binaries
          paths:
            - enmon*

    - stage: deploy
      language: minimal
      script: ls -lha
      workspaces:
        use:
          - linux-binaries
          - osx-binaries
